import {IIngredientWithKey} from "../types";

export const constructorItemFake: IIngredientWithKey = {
    calories: 30,
    carbohydrates: 40,
    countIngredient: 0,
    fat: 20,
    image: "https://code.s3.yandex.net/react/code/sauce-02.png",
    image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
    image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
    key: 0.02577731006719075,
    name: "Соус Spicy-X прикололс",
    price: 90,
    proteins: 30,
    type: "sauce",
    __v: 0,
    _id: "12345678",
};

export const constructorSourceFake: IIngredientWithKey[] = [
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719073,
        name: "Соус Spicy-X",
        price: 190,
        proteins: 30,
        type: "sauce",
        __v: 0,
        _id: "12345",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719072,
        name: "Соус Spicy-X",
        price: 290,
        proteins: 30,
        type: "bun",
        __v: 0,
        _id: "123456",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719071,
        name: "Соус Spicy-X",
        price: 390,
        proteins: 30,
        type: "main",
        __v: 0,
        _id: "1234567",
    },
];

export const constructorAddedIngredientFake: IIngredientWithKey[] = [
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719073,
        name: "Соус Spicy-X",
        price: 190,
        proteins: 30,
        type: "sauce",
        __v: 0,
        _id: "12345",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719072,
        name: "Соус Spicy-X",
        price: 290,
        proteins: 30,
        type: "bun",
        __v: 0,
        _id: "123456",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719071,
        name: "Соус Spicy-X",
        price: 390,
        proteins: 30,
        type: "main",
        __v: 0,
        _id: "1234567",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719075,
        name: "Соус Spicy-X прикололс",
        price: 90,
        proteins: 30,
        type: "sauce",
        __v: 0,
        _id: "12345678",
    }
];

export const constructorDeletedItemFake: IIngredientWithKey[] = [
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719072,
        name: "Соус Spicy-X",
        price: 290,
        proteins: 30,
        type: "bun",
        __v: 0,
        _id: "123456",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719071,
        name: "Соус Spicy-X",
        price: 390,
        proteins: 30,
        type: "main",
        __v: 0,
        _id: "1234567",
    },
];

export const constructorSwappedFake: IIngredientWithKey[] = [

    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719071,
        name: "Соус Spicy-X",
        price: 390,
        proteins: 30,
        type: "main",
        __v: 0,
        _id: "1234567",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719073,
        name: "Соус Spicy-X",
        price: 190,
        proteins: 30,
        type: "sauce",
        __v: 0,
        _id: "12345",
    },
    {
        calories: 30,
        carbohydrates: 40,
        countIngredient: 0,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        key: 0.02577731006719072,
        name: "Соус Spicy-X",
        price: 290,
        proteins: 30,
        type: "bun",
        __v: 0,
        _id: "123456",
    },
];
